import { useRef, useState, useCallback } from 'react';
import { useRouter } from 'next/router';
import AdminLayout from '@/components/layouts/AdminLayout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  CheckCircle2,
  Upload,
  FileSpreadsheet,
  Image as ImageIcon,
  Award,
  ChevronRight,
  ChevronLeft,
  Loader2,
  AlertCircle,
  Users,
  CalendarDays,
  Plus,
  Trash2,
  Settings,
  Mic2,
  Shield,
  Download,
  LayoutTemplate,
} from 'lucide-react';
import { cn } from '@/utils/cn';

// ── Types ─────────────────────────────────────────────────────────────────────

interface ParticipantRow {
  name:      string;
  email:     string;
  company?:  string;
  phone?:    string;
  document?: string;
  badgeRole?: string;
}

interface Speaker {
  id:           string;
  name:         string;
  title:        string;
  org:          string;
  email:        string;
  generateBadge: boolean;
}

interface StaffMember {
  id:    string;
  name:  string;
  role:  string;
  email: string;
}

interface EventDay { date: string; label: string; }

type PeopleTab      = 'participants' | 'speakers' | 'staff';
type TemplateOption = 'default' | 'custom';

// ── Helpers ───────────────────────────────────────────────────────────────────

const uid = () => Math.random().toString(36).slice(2, 10);

const normKey = (s: string) =>
  s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();

function pickField(row: Record<string, string>, ...keys: string[]): string {
  for (const k of keys) {
    for (const rowKey of Object.keys(row)) {
      if (normKey(rowKey) === normKey(k)) return (row[rowKey] ?? '').trim();
    }
  }
  return '';
}

function parseCSVRows(rows: Record<string, string>[]): ParticipantRow[] {
  return rows
    .map((row) => ({
      name:      pickField(row, 'Nome do Aluno', 'nome', 'name', 'Nome').replace(/^\d+\.\s*/, '').trim(),
      email:     pickField(row, 'E-mail', 'email', 'Email', 'e-mail').toLowerCase(),
      company:   pickField(row, 'Órgão Público', 'orgao publico', 'empresa', 'company') || undefined,
      phone:     pickField(row, 'Telefone', 'telefone', 'phone') || undefined,
      document:  pickField(row, 'CPF', 'cpf', 'documento', 'document') || undefined,
      badgeRole: pickField(row, 'funcao', 'role', 'Função') || 'Participante',
    }))
    .filter((r) => r.name && r.email);
}

function autoGenerateDays(startDate: string, endDate: string): EventDay[] {
  if (!startDate || !endDate) return [];
  const start = new Date(startDate);
  const end   = new Date(endDate);
  if (isNaN(start.getTime()) || isNaN(end.getTime()) || start > end) return [];

  const days: EventDay[] = [];
  const cur  = new Date(start.toISOString().slice(0, 10));
  const last = new Date(end.toISOString().slice(0, 10));
  let i = 1;
  while (cur <= last && days.length < 31) {
    days.push({ date: cur.toISOString().slice(0, 10), label: `Dia ${i++}` });
    cur.setDate(cur.getDate() + 1);
  }
  return days;
}

function downloadCSVTemplate() {
  const blob = new Blob(
    ['Nome do Aluno,E-mail,Órgão Público,Telefone,CPF,Função\n'],
    { type: 'text/csv;charset=utf-8;' },
  );
  const a = Object.assign(document.createElement('a'), {
    href:     URL.createObjectURL(blob),
    download: 'modelo-participantes.csv',
  });
  a.click();
  URL.revokeObjectURL(a.href);
}

// ── Step indicator ────────────────────────────────────────────────────────────

const STEPS = [
  { label: 'Informações' },
  { label: 'Pessoas'     },
  { label: 'Aparência'   },
  { label: 'Revisão'     },
];

function StepBar({ current }: { current: number }) {
  return (
    <div className="flex items-center mb-8">
      {STEPS.map(({ label }, i) => (
        <div key={i} className="flex items-center flex-1 last:flex-none">
          <div className="flex flex-col items-center gap-1">
            <div
              className={cn(
                'w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold border-2 transition-all',
                i < current  && 'bg-primary border-primary text-primary-foreground',
                i === current && 'border-primary text-primary bg-surface',
                i > current  && 'border-muted text-muted-foreground/40 bg-background',
              )}
            >
              {i < current ? <CheckCircle2 className="w-4 h-4" /> : i + 1}
            </div>
            <span
              className={cn(
                'text-[11px] font-medium whitespace-nowrap',
                i === current ? 'text-primary' : 'text-muted-foreground/40',
              )}
            >
              {label}
            </span>
          </div>
          {i < STEPS.length - 1 && (
            <div
              className={cn(
                'flex-1 h-0.5 mx-2 mb-4 transition-colors',
                i < current ? 'bg-primary' : 'bg-muted',
              )}
            />
          )}
        </div>
      ))}
    </div>
  );
}

// ── Reusable mini-components ──────────────────────────────────────────────────

function SectionHeader({
  icon: Icon,
  title,
  subtitle,
}: {
  icon: React.ElementType;
  title: string;
  subtitle?: string;
}) {
  return (
    <div className="flex items-start gap-2 mb-1">
      <Icon className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
      <div>
        <h2 className="font-semibold text-foreground text-sm">{title}</h2>
        {subtitle && <p className="text-xs text-muted-foreground mt-0.5">{subtitle}</p>}
      </div>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  sub,
  span2,
}: {
  label: string;
  value: string;
  sub?: string;
  span2?: boolean;
}) {
  return (
    <div className={cn('rounded-lg border border-border bg-muted/30 p-3', span2 && 'col-span-2')}>
      <p className="text-[11px] text-muted-foreground mb-0.5">{label}</p>
      <p className="font-semibold text-foreground text-sm leading-snug">{value || '—'}</p>
      {sub && <p className="text-[11px] text-muted-foreground mt-0.5">{sub}</p>}
    </div>
  );
}

interface TemplateSectionProps {
  icon:        React.ElementType;
  iconColor:   string;
  title:       string;
  option:      TemplateOption;
  setOption:   (v: TemplateOption) => void;
  uploading:   boolean;
  uploadedUrl: string;
  uploadedName: string;
  fileRef:     React.RefObject<HTMLInputElement>;
  onSelectFile: (file: File) => void;
}

function TemplateSection({
  icon: Icon,
  iconColor,
  title,
  option,
  setOption,
  uploading,
  uploadedUrl,
  uploadedName,
  fileRef,
  onSelectFile,
}: TemplateSectionProps) {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <Icon className={cn('w-4 h-4', iconColor)} />
        <span className="font-medium text-sm text-foreground">{title}</span>
      </div>

      <div className="flex rounded-md border border-border overflow-hidden text-xs font-medium">
        {(['default', 'custom'] as const).map((opt) => (
          <button
            key={opt}
            type="button"
            onClick={() => setOption(opt)}
            className={cn(
              'flex-1 py-2 transition-colors',
              option === opt
                ? 'bg-primary text-primary-foreground'
                : 'bg-surface text-muted-foreground hover:bg-muted',
            )}
          >
            {opt === 'default' ? 'Usar padrão do sistema' : 'Enviar arte própria'}
          </button>
        ))}
      </div>

      {option === 'default' ? (
        <div className="rounded-lg border border-dashed border-border p-5 text-center bg-muted/20">
          <LayoutTemplate className="w-6 h-6 mx-auto mb-2 text-muted-foreground/40" />
          <p className="text-xs text-muted-foreground">O sistema usará o modelo padrão.</p>
          <p className="text-[11px] text-muted-foreground/70 mt-0.5">
            Você pode personalizar depois no editor de templates.
          </p>
        </div>
      ) : (
        <>
          <button
            type="button"
            onClick={() => fileRef.current?.click()}
            disabled={uploading}
            className={cn(
              'w-full border-2 border-dashed rounded-lg p-5 text-center text-xs cursor-pointer transition-colors flex flex-col items-center gap-2',
              uploadedUrl
                ? 'border-green-400 bg-green-50/60 text-green-700'
                : 'border-border hover:border-primary/40 hover:bg-muted/20 text-muted-foreground',
            )}
          >
            {uploading ? (
              <><Loader2 className="w-6 h-6 animate-spin" /><span>Enviando...</span></>
            ) : uploadedUrl ? (
              <><CheckCircle2 className="w-6 h-6 text-green-500" /><span className="font-medium">{uploadedName}</span></>
            ) : (
              <><Upload className="w-6 h-6" /><span className="font-medium">Selecionar arquivo</span><span className="text-[11px]">JPEG · PNG · PDF</span></>
            )}
          </button>
          <input
            ref={fileRef}
            type="file"
            accept=".jpg,.jpeg,.png,.pdf"
            className="hidden"
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) onSelectFile(f);
            }}
          />
        </>
      )}
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function CriarEventoPage() {
  const router = useRouter();
  const [step, setStep] = useState(0);

  // ── Step 1 state ────────────────────────────────────────────────────────────
  const [form, setFormState] = useState({
    name:                '',
    eventType:           '',
    startDate:           '',
    endDate:             '',
    city:                '',
    location:            '',
    description:         '',
    address:             '',
    workload:            '',
    checkinWindowMinutes: '60',
  });
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [days, setDays] = useState<EventDay[]>([]);

  // ── Step 2 state ────────────────────────────────────────────────────────────
  const [peopleTab,    setPeopleTab]    = useState<PeopleTab>('participants');
  const [participants, setParticipants] = useState<ParticipantRow[]>([]);
  const [csvFileName,  setCsvFileName]  = useState('');
  const [speakers,     setSpeakers]     = useState<Speaker[]>([]);
  const [newSpeaker,   setNewSpeaker]   = useState({ name: '', title: '', org: '', email: '', generateBadge: true });
  const [staff,        setStaff]        = useState<StaffMember[]>([]);
  const [newStaff,     setNewStaff]     = useState({ name: '', role: '', email: '' });

  // ── Step 3 state ────────────────────────────────────────────────────────────
  const [badgeOption,    setBadgeOption]    = useState<TemplateOption>('default');
  const [certOption,     setCertOption]     = useState<TemplateOption>('default');
  const [badgeUrl,       setBadgeUrl]       = useState('');
  const [badgeName,      setBadgeName]      = useState('');
  const [certUrl,        setCertUrl]        = useState('');
  const [certName,       setCertName]       = useState('');
  const [uploadingBadge, setUploadingBadge] = useState(false);
  const [uploadingCert,  setUploadingCert]  = useState(false);
  const [uploadError,    setUploadError]    = useState('');

  // ── Step 4 state ────────────────────────────────────────────────────────────
  const [importing,    setImporting]    = useState(false);
  const [importError,  setImportError]  = useState('');
  const [result,       setResult]       = useState<{
    eventId: string; eventName: string; created: number; skipped: number; errors: string[];
  } | null>(null);

  const csvRef   = useRef<HTMLInputElement>(null);
  const badgeRef = useRef<HTMLInputElement>(null);
  const certRef  = useRef<HTMLInputElement>(null);

  // ── Handlers ─────────────────────────────────────────────────────────────────

  const setField = useCallback((field: string, value: string) => {
    setFormState((prev) => {
      const next = { ...prev, [field]: value };
      if (field === 'startDate' || field === 'endDate') {
        const s = field === 'startDate' ? value : prev.startDate;
        const e = field === 'endDate'   ? value : prev.endDate;
        setDays(autoGenerateDays(s, e));
      }
      return next;
    });
  }, []);

  const handleCSV = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setCsvFileName(file.name);
    const Papa = (await import('papaparse')).default;
    Papa.parse(file, {
      header:         true,
      skipEmptyLines: true,
      complete: (r) => setParticipants(parseCSVRows(r.data as Record<string, string>[])),
    });
  };

  const uploadImage = async (
    file: File,
    setUrl:     (u: string) => void,
    setName:    (n: string) => void,
    setLoading: (v: boolean) => void,
  ) => {
    setLoading(true);
    setUploadError('');
    try {
      const fd = new FormData();
      fd.append('file', file);
      const res  = await fetch('/api/upload', { method: 'POST', body: fd });
      const data = await res.json();
      if (!res.ok) { setUploadError(data.error ?? 'Erro no upload. Tente novamente.'); return; }
      setUrl(data.url ?? '');
      setName(file.name);
    } catch {
      setUploadError('Falha de conexão. Tente novamente.');
    } finally {
      setLoading(false);
    }
  };

  const addSpeaker = () => {
    if (!newSpeaker.name || !newSpeaker.email) return;
    setSpeakers((s) => [...s, { id: uid(), ...newSpeaker }]);
    setNewSpeaker({ name: '', title: '', org: '', email: '', generateBadge: true });
  };

  const addStaff = () => {
    if (!newStaff.name) return;
    setStaff((s) => [...s, { id: uid(), ...newStaff }]);
    setNewStaff({ name: '', role: '', email: '' });
  };

  const handleImport = async () => {
    setImporting(true);
    setImportError('');
    try {
      const speakerParticipants: ParticipantRow[] = speakers
        .filter((s) => s.generateBadge)
        .map((s) => ({
          name:      s.name,
          email:     s.email,
          company:   s.org   || undefined,
          badgeRole: s.title || 'Palestrante',
        }));

      const staffParticipants: ParticipantRow[] = staff
        .filter((s) => s.email)
        .map((s) => ({
          name:      s.name,
          email:     s.email,
          badgeRole: s.role || 'Staff',
        }));

      const body = {
        event: {
          name:                form.name,
          description:         form.description         || undefined,
          location:            form.location            || undefined,
          address:             form.address             || undefined,
          city:                form.city                || undefined,
          instructor:          speakers[0]?.name        || undefined,
          workload:            form.workload ? Number(form.workload) : undefined,
          startDate:           form.startDate,
          endDate:             form.endDate,
          checkinWindowMinutes: Number(form.checkinWindowMinutes) || 60,
          days:                days.length > 0 ? days : undefined,
        },
        participants:          [...participants, ...speakerParticipants, ...staffParticipants],
        badgeTemplateUrl:      badgeOption === 'custom' && badgeUrl ? badgeUrl : undefined,
        certificateTemplateUrl: certOption === 'custom' && certUrl  ? certUrl  : undefined,
      };

      const res  = await fetch('/api/events/import-full', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify(body),
      });
      const data = await res.json();
      if (!res.ok) setImportError(data.error ?? 'Erro desconhecido');
      else          setResult(data);
    } catch (e) {
      setImportError(String(e));
    } finally {
      setImporting(false);
    }
  };

  const canProceedStep1 =
    form.name && form.eventType && form.startDate && form.endDate && form.city && form.location;

  const totalPeople = participants.length + speakers.length + staff.length;

  // ── Result screen ─────────────────────────────────────────────────────────

  if (result) {
    return (
      <AdminLayout title="Criar Evento">
        <div className="max-w-2xl mx-auto">
          <Card>
            <CardContent className="p-8 space-y-6">
              <div className="flex items-start gap-4 rounded-xl bg-green-50 border border-green-200 p-5">
                <CheckCircle2 className="w-9 h-9 text-green-500 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-green-800 text-base">Evento criado com sucesso!</p>
                  <p className="text-sm text-green-700 mt-0.5">
                    <strong>{result.eventName}</strong> está pronto para operar.
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="p-3 rounded-lg bg-green-50 border border-green-200">
                  <p className="text-2xl font-bold text-green-700">{result.created}</p>
                  <p className="text-xs text-green-600 mt-0.5">Participantes criados</p>
                </div>
                <div className="p-3 rounded-lg bg-yellow-50 border border-yellow-200">
                  <p className="text-2xl font-bold text-yellow-700">{result.skipped}</p>
                  <p className="text-xs text-yellow-600 mt-0.5">Ignorados (duplicados)</p>
                </div>
                <div className="p-3 rounded-lg bg-red-50 border border-red-200">
                  <p className="text-2xl font-bold text-red-700">{result.errors.length}</p>
                  <p className="text-xs text-red-600 mt-0.5">Erros</p>
                </div>
              </div>

              {result.errors.length > 0 && (
                <div className="rounded-lg bg-red-50 border border-red-200 p-3 text-xs text-red-700 space-y-1 max-h-36 overflow-y-auto">
                  {result.errors.map((e, i) => <p key={i}>{e}</p>)}
                </div>
              )}

              <div className="flex gap-3 pt-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => router.push(`/admin/participants?eventId=${result.eventId}`)}
                >
                  Ver Participantes
                </Button>
                <Button
                  className="flex-1"
                  onClick={() => router.push('/admin/badges')}
                >
                  Gerar Crachás
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </AdminLayout>
    );
  }

  // ── Wizard ────────────────────────────────────────────────────────────────

  return (
    <AdminLayout
      title="Criar Evento"
      description="Configure seu evento passo a passo — sem complicação"
    >
      <div className="max-w-3xl mx-auto">
        <StepBar current={step} />

        {/* ── STEP 1 ── Informações Básicas ──────────────────────────────── */}
        {step === 0 && (
          <Card>
            <CardContent className="p-6 space-y-5">
              <SectionHeader
                icon={CalendarDays}
                title="Informações do Evento"
                subtitle="Campos obrigatórios marcados com *"
              />

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-2 space-y-1.5">
                  <Label>Nome do Evento <span className="text-destructive">*</span></Label>
                  <Input
                    placeholder="Ex: Encontro Nacional do Poder Legislativo Municipal"
                    value={form.name}
                    onChange={(e) => setField('name', e.target.value)}
                  />
                </div>

                <div className="space-y-1.5">
                  <Label>Tipo de Evento <span className="text-destructive">*</span></Label>
                  <Select value={form.eventType} onValueChange={(v) => setField('eventType', v)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Selecione..." />
                    </SelectTrigger>
                    <SelectContent>
                      {['Curso', 'Congresso', 'Seminário', 'Workshop', 'Palestra', 'Conferência', 'Outro'].map(
                        (t) => <SelectItem key={t} value={t}>{t}</SelectItem>,
                      )}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1.5">
                  <Label>Cidade <span className="text-destructive">*</span></Label>
                  <Input
                    placeholder="Ex: Brasília - DF"
                    value={form.city}
                    onChange={(e) => setField('city', e.target.value)}
                  />
                </div>

                <div className="sm:col-span-2 space-y-1.5">
                  <Label>Local / Venue <span className="text-destructive">*</span></Label>
                  <Input
                    placeholder="Ex: Centro de Convenções Ulysses Guimarães"
                    value={form.location}
                    onChange={(e) => setField('location', e.target.value)}
                  />
                </div>

                <div className="space-y-1.5">
                  <Label>Início <span className="text-destructive">*</span></Label>
                  <Input
                    type="datetime-local"
                    value={form.startDate}
                    onChange={(e) => setField('startDate', e.target.value)}
                  />
                </div>

                <div className="space-y-1.5">
                  <Label>Fim <span className="text-destructive">*</span></Label>
                  <Input
                    type="datetime-local"
                    value={form.endDate}
                    onChange={(e) => setField('endDate', e.target.value)}
                  />
                </div>
              </div>

              {/* ── Auto-generated days ───────────────────────────────────── */}
              {days.length > 0 && (
                <div className="space-y-2.5 pt-3 border-t border-border">
                  <div className="flex items-center gap-1.5">
                    <CalendarDays className="w-3.5 h-3.5 text-primary" />
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
                      {days.length === 1
                        ? '1 dia gerado automaticamente'
                        : `${days.length} dias gerados automaticamente`}
                      {' '}— edite os nomes se quiser
                    </p>
                  </div>
                  <div className="space-y-2">
                    {days.map((d, i) => (
                      <div
                        key={i}
                        className="flex items-center gap-3 bg-muted/40 rounded-lg px-3 py-2"
                      >
                        <span className="text-xs text-muted-foreground font-mono w-24 shrink-0">
                          {d.date}
                        </span>
                        <Input
                          value={d.label}
                          onChange={(e) =>
                            setDays((prev) =>
                              prev.map((day, idx) =>
                                idx === i ? { ...day, label: e.target.value } : day,
                              ),
                            )
                          }
                          className="h-7 text-sm"
                        />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* ── Advanced settings (collapsible) ──────────────────────── */}
              <div className="border-t border-border pt-3">
                <button
                  type="button"
                  onClick={() => setShowAdvanced((v) => !v)}
                  className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  <Settings className="w-3.5 h-3.5" />
                  {showAdvanced ? 'Ocultar configurações avançadas' : 'Configurações avançadas (opcional)'}
                  <ChevronRight
                    className={cn('w-3.5 h-3.5 transition-transform', showAdvanced && 'rotate-90')}
                  />
                </button>

                {showAdvanced && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                    <div className="sm:col-span-2 space-y-1.5">
                      <Label>Descrição</Label>
                      <Textarea
                        placeholder="Descreva o objetivo e o conteúdo do evento..."
                        value={form.description}
                        onChange={(e) => setField('description', e.target.value)}
                        className="resize-none"
                        rows={3}
                      />
                    </div>
                    <div className="sm:col-span-2 space-y-1.5">
                      <Label>Endereço Completo</Label>
                      <Input
                        placeholder="Rua, número, bairro..."
                        value={form.address}
                        onChange={(e) => setField('address', e.target.value)}
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label>Carga Horária (horas)</Label>
                      <Input
                        type="number"
                        min="1"
                        placeholder="Ex: 40"
                        value={form.workload}
                        onChange={(e) => setField('workload', e.target.value)}
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label>Janela de Check-in (minutos antes do início)</Label>
                      <Input
                        type="number"
                        min="0"
                        value={form.checkinWindowMinutes}
                        onChange={(e) => setField('checkinWindowMinutes', e.target.value)}
                      />
                    </div>
                  </div>
                )}
              </div>

              <div className="flex justify-end pt-2">
                <Button onClick={() => setStep(1)} disabled={!canProceedStep1} className="gap-2">
                  Próximo: Pessoas <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* ── STEP 2 ── Pessoas do Evento ────────────────────────────────── */}
        {step === 1 && (
          <Card>
            <CardContent className="p-6 space-y-5">
              <SectionHeader
                icon={Users}
                title="Pessoas do Evento"
                subtitle="Participantes são obrigatórios. Palestrantes e staff são opcionais."
              />

              {/* People tabs */}
              <div className="flex rounded-lg border border-border overflow-hidden text-xs font-medium">
                {(
                  [
                    {
                      key:   'participants' as const,
                      label: participants.length ? `Participantes (${participants.length})` : 'Participantes',
                      icon:  Users,
                    },
                    {
                      key:   'speakers' as const,
                      label: speakers.length ? `Palestrantes (${speakers.length})` : 'Palestrantes',
                      icon:  Mic2,
                    },
                    {
                      key:   'staff' as const,
                      label: staff.length ? `Staff (${staff.length})` : 'Staff',
                      icon:  Shield,
                    },
                  ]
                ).map(({ key, label, icon: Icon }) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => setPeopleTab(key)}
                    className={cn(
                      'flex-1 flex items-center justify-center gap-1.5 py-2 transition-colors border-r last:border-r-0 border-border',
                      peopleTab === key
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-surface text-muted-foreground hover:bg-muted',
                    )}
                  >
                    <Icon className="w-3.5 h-3.5" />
                    <span className="hidden sm:inline">{label}</span>
                    <span className="sm:hidden">{key === 'participants' ? 'Partic.' : key === 'speakers' ? 'Palest.' : 'Staff'}</span>
                  </button>
                ))}
              </div>

              {/* ── Participants tab ──────────────────────────────────────── */}
              {peopleTab === 'participants' && (
                <div className="space-y-4">
                  <div className="flex items-start justify-between gap-3">
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      Importe uma planilha CSV ou Excel. As colunas reconhecidas são:{' '}
                      <code className="bg-muted px-1 rounded">Nome do Aluno</code>,{' '}
                      <code className="bg-muted px-1 rounded">E-mail</code>,{' '}
                      <code className="bg-muted px-1 rounded">Órgão Público</code>,{' '}
                      <code className="bg-muted px-1 rounded">Telefone</code>.
                    </p>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={downloadCSVTemplate}
                      className="gap-1.5 shrink-0"
                    >
                      <Download className="w-3.5 h-3.5" />
                      Baixar modelo
                    </Button>
                  </div>

                  <button
                    type="button"
                    onClick={() => csvRef.current?.click()}
                    className={cn(
                      'w-full border-2 border-dashed rounded-xl p-7 text-center cursor-pointer flex flex-col items-center gap-2 transition-colors',
                      participants.length > 0
                        ? 'border-green-400 bg-green-50/60 text-green-700'
                        : 'border-border hover:border-primary/40 hover:bg-muted/20 text-muted-foreground',
                    )}
                  >
                    {participants.length > 0 ? (
                      <>
                        <CheckCircle2 className="w-8 h-8 text-green-500" />
                        <p className="font-semibold text-base">{participants.length} participantes detectados</p>
                        <p className="text-xs">{csvFileName} — clique para trocar</p>
                      </>
                    ) : (
                      <>
                        <FileSpreadsheet className="w-8 h-8" />
                        <p className="font-medium">Clique para selecionar o arquivo</p>
                        <p className="text-xs">Suporte a .csv e .xlsx</p>
                      </>
                    )}
                  </button>
                  <input
                    ref={csvRef}
                    type="file"
                    accept=".csv,.xlsx"
                    className="hidden"
                    onChange={handleCSV}
                  />

                  {/* Preview table */}
                  {participants.length > 0 && (
                    <div className="rounded-lg border border-border overflow-hidden">
                      <div className="px-4 py-2 bg-muted/50 border-b border-border flex items-center gap-1.5">
                        <Users className="w-3.5 h-3.5 text-muted-foreground" />
                        <span className="text-xs font-semibold text-muted-foreground">
                          Preview — primeiros 8 registros
                        </span>
                        {participants.length > 8 && (
                          <span className="ml-auto text-xs text-muted-foreground">
                            + {participants.length - 8} restantes
                          </span>
                        )}
                      </div>
                      <div className="overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="border-b border-border bg-muted/20">
                              {['Nome', 'E-mail', 'Órgão', 'Telefone'].map((h) => (
                                <th key={h} className="text-left px-3 py-2 font-medium text-muted-foreground">
                                  {h}
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-border">
                            {participants.slice(0, 8).map((p, i) => (
                              <tr key={i} className="hover:bg-muted/10 transition-colors">
                                <td className="px-3 py-2 font-medium text-foreground max-w-[180px] truncate">
                                  {p.name}
                                </td>
                                <td className="px-3 py-2 text-muted-foreground max-w-[160px] truncate">
                                  {p.email}
                                </td>
                                <td className="px-3 py-2 text-muted-foreground max-w-[140px] truncate">
                                  {p.company || '—'}
                                </td>
                                <td className="px-3 py-2 text-muted-foreground">
                                  {p.phone || '—'}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* ── Speakers tab ──────────────────────────────────────────── */}
              {peopleTab === 'speakers' && (
                <div className="space-y-4">
                  <p className="text-xs text-muted-foreground">
                    Adicione palestrantes e instrutores. Eles receberão crachá com seu cargo e serão
                    incluídos na lista de participantes.
                  </p>

                  {speakers.map((s) => (
                    <div
                      key={s.id}
                      className="flex items-center gap-3 bg-muted/30 rounded-lg px-3 py-2.5"
                    >
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground">{s.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {[s.title, s.org].filter(Boolean).join(' · ')}
                        </p>
                      </div>
                      {s.generateBadge && (
                        <span className="text-[11px] bg-primary/10 text-primary px-2 py-0.5 rounded-full shrink-0">
                          Crachá
                        </span>
                      )}
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-destructive hover:text-destructive shrink-0"
                        onClick={() => setSpeakers((prev) => prev.filter((x) => x.id !== s.id))}
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  ))}

                  <div className="rounded-lg border border-border p-4 space-y-3 bg-muted/10">
                    <p className="text-xs font-semibold text-muted-foreground">Adicionar palestrante</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <Input
                        placeholder="Nome *"
                        value={newSpeaker.name}
                        onChange={(e) => setNewSpeaker((s) => ({ ...s, name: e.target.value }))}
                      />
                      <Input
                        placeholder="E-mail *"
                        type="email"
                        value={newSpeaker.email}
                        onChange={(e) => setNewSpeaker((s) => ({ ...s, email: e.target.value }))}
                      />
                      <Input
                        placeholder="Cargo / Tema"
                        value={newSpeaker.title}
                        onChange={(e) => setNewSpeaker((s) => ({ ...s, title: e.target.value }))}
                      />
                      <Input
                        placeholder="Organização"
                        value={newSpeaker.org}
                        onChange={(e) => setNewSpeaker((s) => ({ ...s, org: e.target.value }))}
                      />
                    </div>
                    <div className="flex items-center justify-between">
                      <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer select-none">
                        <input
                          type="checkbox"
                          checked={newSpeaker.generateBadge}
                          onChange={(e) =>
                            setNewSpeaker((s) => ({ ...s, generateBadge: e.target.checked }))
                          }
                          className="rounded"
                        />
                        Gerar crachá para este palestrante
                      </label>
                      <Button
                        size="sm"
                        type="button"
                        onClick={addSpeaker}
                        disabled={!newSpeaker.name || !newSpeaker.email}
                        className="gap-1"
                      >
                        <Plus className="w-3 h-3" /> Adicionar
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              {/* ── Staff tab ─────────────────────────────────────────────── */}
              {peopleTab === 'staff' && (
                <div className="space-y-4">
                  <p className="text-xs text-muted-foreground">
                    Cadastre a equipe de apoio. Opcional — útil para gerar crachás de credenciamento
                    interno. Informe o e-mail para incluir na lista.
                  </p>

                  {staff.map((s) => (
                    <div
                      key={s.id}
                      className="flex items-center gap-3 bg-muted/30 rounded-lg px-3 py-2.5"
                    >
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium text-foreground">{s.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {[s.role, s.email].filter(Boolean).join(' · ')}
                        </p>
                      </div>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7 text-destructive hover:text-destructive shrink-0"
                        onClick={() => setStaff((prev) => prev.filter((x) => x.id !== s.id))}
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  ))}

                  <div className="rounded-lg border border-border p-4 space-y-3 bg-muted/10">
                    <p className="text-xs font-semibold text-muted-foreground">
                      Adicionar membro da equipe
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                      <Input
                        placeholder="Nome *"
                        value={newStaff.name}
                        onChange={(e) => setNewStaff((s) => ({ ...s, name: e.target.value }))}
                      />
                      <Input
                        placeholder="Função (Ex: Credenciamento)"
                        value={newStaff.role}
                        onChange={(e) => setNewStaff((s) => ({ ...s, role: e.target.value }))}
                      />
                      <Input
                        placeholder="E-mail (opcional)"
                        type="email"
                        value={newStaff.email}
                        onChange={(e) => setNewStaff((s) => ({ ...s, email: e.target.value }))}
                      />
                    </div>
                    <div className="flex justify-end">
                      <Button
                        size="sm"
                        type="button"
                        onClick={addStaff}
                        disabled={!newStaff.name}
                        className="gap-1"
                      >
                        <Plus className="w-3 h-3" /> Adicionar
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex justify-between pt-3 border-t border-border">
                <Button variant="outline" onClick={() => setStep(0)} className="gap-2">
                  <ChevronLeft className="w-4 h-4" /> Voltar
                </Button>
                <Button
                  onClick={() => setStep(2)}
                  disabled={participants.length === 0}
                  className="gap-2"
                >
                  Próximo: Aparência <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* ── STEP 3 ── Aparência ─────────────────────────────────────────── */}
        {step === 2 && (
          <Card>
            <CardContent className="p-6 space-y-6">
              <SectionHeader
                icon={LayoutTemplate}
                title="Aparência dos Documentos"
                subtitle="Escolha entre usar o modelo padrão do sistema ou enviar sua arte personalizada."
              />

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <TemplateSection
                  icon={ImageIcon}
                  iconColor="text-blue-500"
                  title="Crachá"
                  option={badgeOption}
                  setOption={setBadgeOption}
                  uploading={uploadingBadge}
                  uploadedUrl={badgeUrl}
                  uploadedName={badgeName}
                  fileRef={badgeRef}
                  onSelectFile={(f) =>
                    uploadImage(f, setBadgeUrl, setBadgeName, setUploadingBadge)
                  }
                />
                <TemplateSection
                  icon={Award}
                  iconColor="text-purple-500"
                  title="Certificado"
                  option={certOption}
                  setOption={setCertOption}
                  uploading={uploadingCert}
                  uploadedUrl={certUrl}
                  uploadedName={certName}
                  fileRef={certRef}
                  onSelectFile={(f) =>
                    uploadImage(f, setCertUrl, setCertName, setUploadingCert)
                  }
                />
              </div>

              {uploadError && (
                <div className="flex items-center gap-2 bg-destructive/10 text-destructive rounded-lg px-3 py-2 text-xs">
                  <AlertCircle className="w-3.5 h-3.5 flex-shrink-0" />
                  {uploadError}
                </div>
              )}

              <div className="flex justify-between pt-2 border-t border-border">
                <Button variant="outline" onClick={() => setStep(1)} className="gap-2">
                  <ChevronLeft className="w-4 h-4" /> Voltar
                </Button>
                <Button onClick={() => setStep(3)} className="gap-2">
                  Próximo: Revisão <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* ── STEP 4 ── Revisão e Confirmação ────────────────────────────── */}
        {step === 3 && (
          <Card>
            <CardContent className="p-6 space-y-5">
              <SectionHeader
                icon={CheckCircle2}
                title="Revisão Final"
                subtitle="Confirme tudo antes de criar o evento. Você ainda poderá editar depois."
              />

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                <SummaryCard label="Evento"       value={form.name}     sub={form.eventType} span2 />
                <SummaryCard label="Cidade"       value={form.city}     sub={form.location}        />
                <SummaryCard
                  label="Início"
                  value={form.startDate ? new Date(form.startDate).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}
                />
                <SummaryCard
                  label="Fim"
                  value={form.endDate ? new Date(form.endDate).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}
                />
                <SummaryCard
                  label="Participantes"
                  value={String(participants.length)}
                  sub="detectados da planilha"
                />
                <SummaryCard label="Palestrantes" value={String(speakers.length)} />
                <SummaryCard label="Staff"        value={String(staff.length)}    />
                <SummaryCard
                  label="Crachá"
                  value={badgeOption === 'custom' && badgeUrl ? 'Arte personalizada' : 'Modelo padrão'}
                />
                <SummaryCard
                  label="Certificado"
                  value={certOption === 'custom' && certUrl ? 'Arte personalizada' : 'Modelo padrão'}
                />
              </div>

              {/* Days list */}
              {days.length > 0 && (
                <div className="rounded-lg border border-border overflow-hidden">
                  <div className="px-4 py-2 bg-muted/40 border-b border-border flex items-center gap-1.5">
                    <CalendarDays className="w-3.5 h-3.5 text-muted-foreground" />
                    <span className="text-xs font-semibold text-muted-foreground">
                      {days.length} {days.length === 1 ? 'dia de evento' : 'dias de evento'}
                    </span>
                  </div>
                  <div className="divide-y divide-border max-h-48 overflow-y-auto">
                    {days.map((d, i) => (
                      <div key={i} className="flex items-center justify-between px-4 py-2 text-sm">
                        <span className="font-medium text-foreground">{d.label}</span>
                        <span className="text-muted-foreground font-mono text-xs">{d.date}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {totalPeople === 0 && (
                <div className="flex items-center gap-2 bg-yellow-50 border border-yellow-200 text-yellow-800 rounded-lg px-3 py-2 text-xs">
                  <AlertCircle className="w-3.5 h-3.5 flex-shrink-0" />
                  Nenhum participante importado. Volte à etapa Pessoas e importe uma planilha.
                </div>
              )}

              {importError && (
                <div className="flex items-start gap-2 bg-destructive/10 text-destructive rounded-lg p-3 text-sm">
                  <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
                  <span>{importError}</span>
                </div>
              )}

              <div className="flex justify-between pt-2 border-t border-border">
                <Button
                  variant="outline"
                  onClick={() => setStep(2)}
                  disabled={importing}
                  className="gap-2"
                >
                  <ChevronLeft className="w-4 h-4" /> Voltar
                </Button>
                <Button
                  onClick={handleImport}
                  disabled={importing || totalPeople === 0}
                  className="gap-2 min-w-[170px]"
                >
                  {importing ? (
                    <><Loader2 className="w-4 h-4 animate-spin" /> Criando evento...</>
                  ) : (
                    <><CheckCircle2 className="w-4 h-4" /> Confirmar e Criar</>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </AdminLayout>
  );
}
